# Generated by Django 5.2.5 on 2025-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attack_power', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='enemies',
            field=models.ManyToManyField(to='mainapp.enemy'),
        ),
    ]
