# Generated by Django 5.2.5 on 2025-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_enemy_hero_enemies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='attack_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
